### ISSUE TITLE
Couldn't train the network (covariance_market1501.py)

### ISSUE THREAD

**Issue by sugiantonehemia** [prajjwal1/person-reid-lwf#2]
Hi Prajjwal, 

Found that your paper is really insteresting but couldn't perform the training on Market1501 due to this error. Spent a lot of hours to resolve it but didn't find the cause

```
Model is being initialized
Model size: 203.81197M
Training of model in progress
Dataset is being initialized
=> DukeMTMC-reID loaded
Dataset statistics:
  ------------------------------
  subset   | # ids | # images
  ------------------------------
  train    |   751 |    12936
  query    |   750 |     3368
  gallery  |   752 |    19732
  ------------------------------
  total    |  1501 |    36036
  ------------------------------
Model is being initialized
Model size: 203.81197M
Training of model in progress
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Anaconda3\envs\py36gpuwithgraphvis_irenne_2\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Anaconda3\envs\py36gpuwithgraphvis_irenne_2\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Anaconda3\envs\py36gpuwithgraphvis_irenne_2\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Anaconda3\envs\py36gpuwithgraphvis_irenne_2\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Anaconda3\envs\py36gpuwithgraphvis_irenne_2\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Anaconda3\envs\py36gpuwithgraphvis_irenne_2\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Anaconda3\envs\py36gpuwithgraphvis_irenne_2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Data\Program\Tensorflow_Keras\People_ReIdentification\ResNet50_on_Pytorch\covariance_market1501.py", line 390, in <module>
    train(epoch,model,optim,trainloader)
  File "E:\Data\Program\Tensorflow_Keras\People_ReIdentification\ResNet50_on_Pytorch\covariance_market1501.py", line 153, in train
    for batch,(imgs,pids,camids) in enumerate(trainloader):
  File "C:\Anaconda3\envs\py36gpuwithgraphvis_irenne_2\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __iter__
    return _DataLoaderIter(self)
  File "C:\Anaconda3\envs\py36gpuwithgraphvis_irenne_2\lib\site-packages\torch\utils\data\dataloader.py", line 560, in __init__
    w.start()
  File "C:\Anaconda3\envs\py36gpuwithgraphvis_irenne_2\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Anaconda3\envs\py36gpuwithgraphvis_irenne_2\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Anaconda3\envs\py36gpuwithgraphvis_irenne_2\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Anaconda3\envs\py36gpuwithgraphvis_irenne_2\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Anaconda3\envs\py36gpuwithgraphvis_irenne_2\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Anaconda3\envs\py36gpuwithgraphvis_irenne_2\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "covariance_market1501.py", line 390, in <module>
    train(epoch,model,optim,trainloader)
  File "covariance_market1501.py", line 153, in train
    for batch,(imgs,pids,camids) in enumerate(trainloader):
  File "C:\Anaconda3\envs\py36gpuwithgraphvis_irenne_2\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __iter__
    return _DataLoaderIter(self)
  File "C:\Anaconda3\envs\py36gpuwithgraphvis_irenne_2\lib\site-packages\torch\utils\data\dataloader.py", line 560, in __init__
    w.start()
  File "C:\Anaconda3\envs\py36gpuwithgraphvis_irenne_2\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Anaconda3\envs\py36gpuwithgraphvis_irenne_2\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Anaconda3\envs\py36gpuwithgraphvis_irenne_2\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Anaconda3\envs\py36gpuwithgraphvis_irenne_2\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Anaconda3\envs\py36gpuwithgraphvis_irenne_2\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by prajjwal1** [comment]
Hi, Thanks for the feedback, it's more of a Pytorch related issue. You can try going through their issues section. 
I found related issues
- [1](https://github.com/pytorch/pytorch/issues/2341)
- [2](https://github.com/pytorch/pytorch/issues/4418)
Are you using Windows ? Also Try setting num_workers to 0. Let me know if it fixes it .
